# Project: kiwi_SP
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o fat-reader.o fat-writer.o
LINKOBJ  = main.o fat-reader.o fat-writer.o
LIBS     = -L"E:/INSTALL_DEV/Dev-Cpp/MinGW64/lib" -L"E:/INSTALL_DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/include" -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/include" -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/INSTALL_DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = kiwi_SP.exe
CXXFLAGS = $(CXXINCS) -ansi
CFLAGS   = $(INCS) -ansi
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

fat-reader.o: fat-reader.c
	$(CC) -c fat-reader.c -o fat-reader.o $(CFLAGS)

fat-writer.o: fat-writer.c
	$(CC) -c fat-writer.c -o fat-writer.o $(CFLAGS)
